version:  "3"

services:
  # postgres:
  #   image: postgres:14
  #   environment:
  #     - "POSTGRES_PASSWORD=SU2orange!"
  #     - POSTGRES_USER=sa
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  mssql:
#    image: mcr.microsoft.com/azure-sql-edge:latest
    image: mcr.microsoft.com/mssql/server:2019-latest
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=SU2orange!"
    ports:
      - "1433:1433"
    hostname: mssql
    volumes:
      - "mssql-azuresql-edge-data:/var/opt/mssql"
#      - "mssql-2017-data:/var/opt/mssql"
    networks: 
      - "learndb_net"
  webapp:    
#    platform: linux/amd64
    build: app/.
    environment:
#      - "CONNSTR=DRIVER={ODBC Driver 17 for SQL Server};SERVER=mssql,1433;DATABASE=master;UID=sa;PWD=SU2orange!"
      - "FLASK_APP=app.py"
      - "FLASK_ENV=development"
      - "SCHEMA_PATH=/app/schemas"
      - "SQL_CLIENT_HOST=mssql"
      - "SQL_CLIENT_PORT=1433"
      - "SQL_CLIENT_USER=sa"
      - "SQL_CLIENT_PASS=SU2orange!"
      - "SQL_CLIENT_CMD=/opt/mssql-tools/bin/sqlcmd"
      - "RANDOM_SEED=0"
    ports: 
      - "5001:8000"
    links:
      - mssql
    volumes:
      - "./app/:/app/" # for now
      - "./schemas:/app/schemas"
    networks: 
      - "learndb_net"
  sqlpad:
    image: sqlpad/sqlpad:6.7.1 #5.6
    environment:
      - "SQLPAD_ADMIN=admin@admin.org"
      - "SQLPAD_ADMIN_PASSWORD=SU2orange!"
      - "SQLPAD_AUTH_DISABLED=True"
      - "SQLPAD_AUTH_DISABLED_DEFAULT_ROLE=admin"
    links:
      - mssql
    ports:
      - "5002:3000"
    volumes:
      - sqlpad-volume:/var/lib/sqlpad
    networks: 
      - "learndb_net"
  adminer:
 #   platform: linux/amd64
    build: adminer/.
    ports:
      - "5003:8080"
    links:
      - mssql
    networks:
      - "learndb_net"

#  superset:
#    build: superset/.
#    links:
#      - mssql
#    ports:
#      - "5088:8088"
#  omnidb:
#    image: t4skforce/omnidb:latest
#    links:
#      - mssql
#    ports:
#      - "5080:8000"
#      - "25482:25482"
volumes:
    mssql-azuresql-edge-data:
#    mssql-2017-data:
    sqlpad-volume:
    # postgres-data:

networks:
  learndb_net:
    driver: bridge
